using WaterLily
using StaticArrays
using DelimitedFiles
using Printf
using LinearAlgebra
using CUDA

# Helper for polygon SDF (2D)
function sdf_poly(p, vertices)
    d = dot(p-vertices[1], p-vertices[1])
    s = 1.0
    for i in 1:length(vertices)
        j = i % length(vertices) + 1
        vi = vertices[i]; vj = vertices[j]
        e = vj - vi
        w = p - vi
        b = w - e * clamp(dot(w,e)/dot(e,e), 0.0, 1.0)
        d = min(d, dot(b,b))
        # winding number for inside/outside test
        c = [p[2] >= vi[2], p[2] < vj[2], e[1]*w[2] > e[2]*w[1]]
        if all(c) || all(.!c) s *= -1.0 end
    end
    return s * sqrt(d)
end

# Function to define the geometry using Signed Distance Functions (SDFs)
function make_geometry(x2, x3, h, Lx, Ly)
    x10 = 40.0 - Lx/2.0
    x20 = x2 - Lx/2.0
    x30 = x3 - Lx/2.0
    
    # Vertices for the bottom triangle
    v1 = SVector(x10, -Ly/2.0)
    v2 = SVector(x20, h - Ly/2.0)
    v3 = SVector(x30, -Ly/2.0)
    
    # Vertices for the top triangle
    v4 = SVector(x30, Ly/2.0)
    v5 = SVector(x20, Ly/2.0 - h)
    v6 = SVector(x10, Ly/2.0)
    
    return (p, t) -> min(sdf_poly(p, [v1, v2, v3]), sdf_poly(p, [v4, v5, v6]))
end

function run_sim(x2=41, x3=41, h=2; n=(1024, 256), L=(100, 20), U=1.0, use_gpu=false)
    # Define simulation parameters
    Re = 100.0 # Reynolds number
    ν = U * L[2] / Re
    
    # Geometry
    geom = make_geometry(x2, x3, h, L[1], L[2])
    
    # Scaling factor
    s = n[1] / L[1]
    
    body = AutoBody((p, t) -> geom((p .- SVector(n[1]/2, n[2]/2)) ./ s, t) * s)
    
    # Setup Simulation (WaterLily handles GPU if mem=CuArray)
    mem = use_gpu ? CuArray : Array
    sim = Simulation(n, (U, 0.0), L[2]*s, body=body, ν=ν*s, mem=mem)
    
    println("Starting simulation on $(use_gpu ? "GPU" : "CPU")...")
    start_time = time()
    sim_step!(sim, 50.0)
    duration = time() - start_time
    println("Simulation converged in $(round(duration, digits=2)) seconds.")
    
    return sim, s, duration
end

# Extract and format data
function export_flow(sim, s, Lx, Ly, out_fname)
    # Extract to CPU for processing and export
    u_raw = Array(sim.flow.u)
    p_raw = Array(sim.flow.p)
    Nx, Ny = size(p_raw) .- 2
    
    ux = zeros(Nx, Ny)
    uy = zeros(Nx, Ny)
    vort = zeros(Nx, Ny)
    
    println("Extracting velocity and calculating vorticity...")
    for i in 1:Nx, j in 1:Ny
        ux[i,j] = 0.5 * (u_raw[i+1, j+1, 1] + u_raw[i+2, j+1, 1])
        uy[i,j] = 0.5 * (u_raw[i+1, j+1, 2] + u_raw[i+1, j+2, 2])
        vort[i,j] = (u_raw[i+2, j+1, 2] - u_raw[i+1, j+1, 2]) - (u_raw[i+1, j+2, 1] - u_raw[i+1, j+1, 1])
    end

    open(out_fname, "w") do f
        for i in 1:9
            println(f, "% Generated by WaterLily.jl - Step $i")
        end
        for i in 1:Nx
            for j in 1:Ny
                px = (i - 0.5 - Nx/2) / s
                py = (j - 0.5 - Ny/2) / s
                @printf(f, "%.6f %.6f %.6f %.6f %.6f\n", px, py, ux[i,j], uy[i,j], vort[i,j])
            end
        end
    end
    println("Exported to $out_fname")
    return ux, uy, vort
end

# Main execution
Lx, Ly = 100.0, 20.0
Nx, Ny = 1024, 256
gpu_avail = CUDA.functional()
sim, s, dur = run_sim(41, 41, 2, n=(Nx, Ny), L=(Lx, Ly), use_gpu=gpu_avail)
ux, uy, vort = export_flow(sim, s, Lx, Ly, "flow_41_41_2.txt")

# Visual proof (Simplified visualization using DelimitedFiles if Plots not ready)
# Or just use a simple ASCII check if we can't install Plots easily here.
# But let's try to use Plots to save a PNG.
try
    using Plots
    p1 = heatmap(vort', title="Vorticity Field (WaterLily)", aspect_ratio=:equal, color=:balance)
    savefig(p1, "flow_vortical_proof.png")
    println("Saved visual proof to flow_vortical_proof.png")
catch e
    println("Plots not available, skipping visual proof generation.")
end
